# Generated by Django 4.0.1 on 2022-06-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_user_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='sort',
            field=models.CharField(default='', max_length=60),
        ),
    ]
