# Generated by Django 4.0.1 on 2022-06-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_dish_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='site_images/')),
                ('description', models.CharField(max_length=300)),
                ('sort', models.CharField(default='', max_length=60)),
            ],
        ),
    ]
