# Generated by Django 4.0.1 on 2022-11-17 15:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_wine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=150)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.CharField(max_length=60)),
                ('guests', models.IntegerField()),
                ('time', models.CharField(max_length=20)),
                ('comment', models.TextField(max_length=2500)),
            ],
        ),
    ]
